verify_signatures: false
CommitMsg:
  CapitalizedSubject:
    enabled: true
    on_warn: fail
  EmptyMessage:
    enabled: true
    on_warn: fail
  SingleLineSubject:
    enabled: true
    on_warn: fail
  TextWidth:
    enabled: true
    on_warn: fail
    max_subject_width: 72
    min_subject_width: 10
  TrailingPeriod:
    enabled: true
    on_warn: fail
PreCommit:
  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/*.md'
  Lint:
    enabled: true
    required_executable: './hooks/lint.sh'
  Test:
    enabled: true
    required_executable: './hooks/test.sh'
