verify_signatures: false
CommitMsg:
  CapitalizedSubject:
    enabled: true
    on_warn: fail
  EmptyMessage:
    enabled: true
    on_warn: fail
  SingleLineSubject:
    enabled: true
    on_warn: fail
  TextWidth:
    enabled: true
    on_warn: fail
    max_subject_width: 72
    min_subject_width: 10
  TrailingPeriod:
    enabled: true
    on_warn: fail
PreCommit:
  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/*.md'
PrePush:
  GitLfs:
    enabled: true
    required_executable: 'git-lfs'
    flags: ['pre-push']
PostCheckout:
  GitLfs:
    enabled: true
    required_executable: 'git-lfs'
    flags: ['post-checkout']
PostCommit:
  GitLfs:
    enabled: true
    required_executable: 'git-lfs'
    flags: ['post-commit']
PostMerge:
  GitLfs:
    enabled: true
    required_executable: 'git-lfs'
    flags: ['post-merge']

